"""Public domain API for the Ascend kernel generation pipeline."""

from .enums import (
    CandidateValidity,
    EvaluationStage,
    ExperimentState,
    JobStatus,
    RoundState,
    TaskState,
)
from .errors import (
    ArtifactConflictError,
    ArtifactIntegrityError,
    ConcurrentUpdateError,
    DomainError,
    IdempotencyConflictError,
    InvalidTransitionError,
    LeaseLostError,
)
from .models import (
    ArtifactMetadata,
    BenchmarkSample,
    CandidateRecord,
    CandidateScore,
    EvaluationJob,
    EventRecord,
    ExperimentRecord,
    JSONValue,
    LeasedEvaluationJob,
    RoundRecord,
    StoredEvaluationJob,
    TaskRecord,
    utc_now,
)
from .scoring import (
    RewardBreakdown,
    aggregate_candidate_score,
    candidate_selection_key,
    compute_reward,
    rank_candidates,
    select_best_candidate,
    weighted_geometric_mean,
)
from .state_machine import (
    RoundStateMachine,
    StrictStateMachine,
    TaskStateMachine,
    round_state_machine,
    task_state_machine,
)

__all__ = [
    "ArtifactConflictError",
    "ArtifactIntegrityError",
    "ArtifactMetadata",
    "BenchmarkSample",
    "CandidateRecord",
    "CandidateScore",
    "CandidateValidity",
    "ConcurrentUpdateError",
    "DomainError",
    "EvaluationJob",
    "EvaluationStage",
    "EventRecord",
    "ExperimentRecord",
    "ExperimentState",
    "IdempotencyConflictError",
    "InvalidTransitionError",
    "JSONValue",
    "JobStatus",
    "LeaseLostError",
    "LeasedEvaluationJob",
    "RewardBreakdown",
    "RoundRecord",
    "RoundState",
    "RoundStateMachine",
    "StoredEvaluationJob",
    "StrictStateMachine",
    "TaskRecord",
    "TaskState",
    "TaskStateMachine",
    "aggregate_candidate_score",
    "candidate_selection_key",
    "compute_reward",
    "rank_candidates",
    "round_state_machine",
    "select_best_candidate",
    "task_state_machine",
    "utc_now",
    "weighted_geometric_mean",
]
